### ISSUE TITLE
CUDA error: too many resources requested for launch

### ISSUE THREAD

**Issue by maoki109** [QwenLM/Qwen2-VL#182]
# Error I’m Facing

```jsx
RuntimeError: CUDA error: too many resources requested for launch
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I am facing this issue when running the "HuggingFace Transformers to Chat" code in the README. Any help to get past this would be greatly appreciated.

## Steps I took

Created and activated a conda environment.

Installed necessary packages: 

`pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830 accelerate` 

`pip install qwen-vl-utils`

`pip install torchvision`

In a Jupyter notebook, put the code from the **Using 🤗 Transformers to Chat** section in the README.

Error above occurs at the line:
`generated_ids = model.generate(**inputs, max_new_tokens=128)`

## What I’ve Tried

1. Tried reducing the GPU memory load by
    1. Adjusting the `padding=True` parameter in the `processor()` call to `padding=False`.
    2. Uncommenting the section to set min_pixels and max_pixels
        
        ```jsx
        min_pixels = 256*28*28
        max_pixels = 1280*28*28
        processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)
        ```
        
2. Adding the following code:

```jsx
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
```

This changed my error from “RuntimeError: CUDA error: too many resources requested for launch
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.” to just “RuntimeError: CUDA error: too many resources requested for launch
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.”

3. Adding `os.environ["TORCH_USE_CUDA_DSA"] = "1"` , similar to previous point. 
4. Utilizing fewer GPUs by changing `device_map="auto"` to `device_map="cuda:0"`. 
5. Setting `max_new_tokens` to a smaller number, all the way down to 2. 
6. Using Qwen2-VL-2B-Instruct instead of Qwen2-VL-7B-Instruct.

## Additional Info

Python 3.12.5

PyTorch 2.4.1+cu121

Ubuntu 20.04.6

Machine has three Tesla V100s (hence why I cannot use Flash Attention 2, as it doesn’t support V100 GPUs).

**Comment by jklj077** [comment]
Hi, 
It is very unfortuate and the error appears to suggest issues with torch's precompiled kernels on V100s. Some have reported that you may be able to work around it by using fp32, e.g., `from_pretrained(..., torch_dtype=torch.float32)`.
However, we are still trying to reproduce the issue. If we can reproduce this, we will see what we can do about this.

**Comment by maoki109** [comment]
Thank you, using a different precision worked for me! I tried it before and it didn't work, but it was because I forgot to add `import torch` (rookie mistake on my part 🤦🏻‍♀️). I really appreciate your help!

For anyone who is reading this thread because of similar issues:
What ended up working for me is (from the original README demo code), changing `torch_dtype="auto"` to `torch_dtype=torch.float32` and uncommenting the code that reduces the number of visual tokens per image:

```
import torch
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct", torch_dtype=torch.float32, device_map="auto"
)

# default processer
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct")

# The default range for the number of visual tokens per image in the model is 4-16384.
# You can set min_pixels and max_pixels according to your needs, such as a token range of 256-1280, to balance performance and cost.
min_pixels = 256*28*28
max_pixels = 1280*28*28
processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)
```

What also worked is changing `torch_dtype` to `torch_dtype=torch.float16` and keeping the default processor:

```
import torch
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct", torch_dtype=torch.float16, device_map="auto"
)

# default processer
processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct")

# The default range for the number of visual tokens per image in the model is 4-16384.
# You can set min_pixels and max_pixels according to your needs, such as a token range of 256-1280, to balance performance and cost.
# min_pixels = 256*28*28
# max_pixels = 1280*28*28
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)
```


This is the output when I run `nvidia-smi` for reference:
```
Thu Sep 12 09:48:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-32GB           On  | 00000000:3B:00.0 Off |                    0 |
| N/A   37C    P0              27W / 250W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE-32GB           On  | 00000000:B1:00.0 Off |                    0 |
| N/A   40C    P0              30W / 250W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE-32GB           On  | 00000000:D9:00.0 Off |                    0 |
| N/A   35C    P0              25W / 250W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by maoki109** [comment]
Closing this issue because I received helpful feedback that resolved my original problem. Thank you!

**Comment by 99991** [comment]
The first suggestion to use float32 did not work for me since Qwen2-VL-7B-Instruct did not fit on a 32GB V100, but the second suggestion to use `torch_dtype=torch.float16` worked well. Thanks!

**Comment by 128veg80** [comment]
I used v100, torch_dtype=torch.float16 worked for me as well. Thank you very much!
