### ISSUE TITLE
多卡推理出现tensor 不在同一张卡的异常提示

### ISSUE THREAD

**Issue by carcloudfly** [QwenLM/Qwen2-VL#234]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:0! (when checking argument for argument mask in method wrapper_CUDA__masked_scatter_)

请问是什么原因，如何修正？

**Comment by ShuaiBai623** [comment]
可以分享分享下出现这个问题的代码以及运行的环境吗

**Comment by carcloudfly** [comment]
CUDA_AVIBLE_DEVICES=0,1,2,3 python web_demo_mm.py -c ../Qwen2-VL-2B-Instruct/ --server-port 8350 --server-name 0.0.0.0
谢谢，环境是这样的。如果只指定 gpu 0 是可以正常运行的。但是容易爆显存。
[requirements_web_demo_locl.txt](https://github.com/user-attachments/files/17069478/requirements_web_demo_locl.txt)

**Comment by carcloudfly** [comment]
不用web demo，用本地脚本，也会出现同样的问题。
# min_pixels = 256*28*28
# max_pixels = 1280*28*28
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

**Comment by thuBingo** [comment]
你好 请问这个问题解决了嘛？ 遇到了相同的问题

**Comment by jiah-li** [comment]
你好 请问这个问题解决了嘛？ 遇到了相同的问题

**Comment by jiah-li** [comment]
我遇到了相同的问题，运行硬件环境为Tesla V100*4，运行指令`CUDA_VISIBLE_DEVICES=0,1,2,3 python start.py`。start.py来租readme中的faststart。
具体代码如下：
`
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info
import torch

# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "/Qwen2-VL-7B-Instruct", torch_dtype=torch.float16, device_map="auto"
)

# We recommend enabling flash_attention_2 for better acceleration and memory saving, especially in multi-image and video scenarios.
# model = Qwen2VLForConditionalGeneration.from_pretrained(
#     "Qwen/Qwen2-VL-7B-Instruct",
#     torch_dtype=torch.bfloat16,
#     attn_implementation="flash_attention_2",
#     device_map="auto",
# )

# default processer
processor = AutoProcessor.from_pretrained("/Qwen2-VL-7B-Instruct")

# The default range for the number of visual tokens per image in the model is 4-16384.
# You can set min_pixels and max_pixels according to your needs, such as a token range of 256-1280, to balance performance and cost.
# min_pixels = 256*28*28
# max_pixels = 1280*28*28
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "/home/users/chenmoye/lijiahui/demo.jpeg",
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]

# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda:0")

import pdb
pdb.set_trace()

# Inference: Generation of the output
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
print(output_text)
`

**Comment by YAwei666** [comment]
解决了吗

**Comment by jiah-li** [comment]
> 解决了吗

解决了，device_map为auto的时候可能会出现问题，使用手动划分就行。可以参考我的：
`
DEVICE_BASE = 2
# visual 和 model.embed_tokens 需要在一张GPU上，否则会报错
_device_map = {'visual': DEVICE_BASE+1, 'model.embed_tokens': DEVICE_BASE+1, 'model.layers.0': DEVICE_BASE, 'model.layers.1': DEVICE_BASE, 'model.layers.2': DEVICE_BASE, 'model.layers.3': DEVICE_BASE, 'model.layers.4': DEVICE_BASE, 'model.layers.5': DEVICE_BASE, 'model.layers.6': DEVICE_BASE, 'model.layers.7': DEVICE_BASE, 'model.layers.8': DEVICE_BASE, 'model.layers.9': DEVICE_BASE, 'model.layers.10': DEVICE_BASE, 'model.layers.11': DEVICE_BASE, 'model.layers.12': DEVICE_BASE, 'model.layers.13': DEVICE_BASE, 'model.layers.14': DEVICE_BASE, 'model.layers.15': DEVICE_BASE, 'model.layers.16': DEVICE_BASE, 'model.layers.17': DEVICE_BASE, 'model.layers.18': DEVICE_BASE, 'model.layers.19': DEVICE_BASE, 'model.layers.20': DEVICE_BASE, 'model.layers.21': DEVICE_BASE, 'model.layers.22': DEVICE_BASE, 'model.layers.23': DEVICE_BASE, 'model.layers.24': DEVICE_BASE, 'model.layers.25': DEVICE_BASE, 'model.layers.26': DEVICE_BASE, 'model.layers.27': DEVICE_BASE, 'model.norm' : DEVICE_BASE, 'model.rotary_emb': DEVICE_BASE, 'lm_head': DEVICE_BASE}

os.environ["CUDA_VISIBLE_DEVICES"] = '0,1,2,3,4'
`

**Comment by Zara7hus7ra** [comment]
两卡推理
`_device_map = {'visual': DEVICE_BASE+1, 'model.embed_tokens': DEVICE_BASE+1, 'model.layers.0': DEVICE_BASE, 'model.layers.1': DEVICE_BASE, 'model.layers.2': DEVICE_BASE, 'model.layers.3': DEVICE_BASE, 'model.layers.4': DEVICE_BASE, 'model.layers.5': DEVICE_BASE, 'model.layers.6': DEVICE_BASE, 'model.layers.7': DEVICE_BASE, 'model.layers.8': DEVICE_BASE, 'model.layers.9': DEVICE_BASE, 'model.layers.10': DEVICE_BASE, 'model.layers.11': DEVICE_BASE, 'model.layers.12': DEVICE_BASE, 'model.layers.13': DEVICE_BASE, 'model.layers.14': DEVICE_BASE, 'model.layers.15': DEVICE_BASE, 'model.layers.16': DEVICE_BASE, 'model.layers.17': DEVICE_BASE, 'model.layers.18': DEVICE_BASE, 'model.layers.19': DEVICE_BASE, 'model.layers.20': DEVICE_BASE, 'model.layers.21': DEVICE_BASE, 'model.layers.22': DEVICE_BASE, 'model.layers.23': DEVICE_BASE, 'model.layers.24': DEVICE_BASE, 'model.layers.25': DEVICE_BASE, 'model.layers.26': DEVICE_BASE, 'model.layers.27': DEVICE_BASE, 'model.norm' : DEVICE_BASE, 'model.rotary_emb': DEVICE_BASE, 'lm_head': DEVICE_BASE}
os.environ["CUDA_VISIBLE_DEVICES"] = "3,4"`
手动划分之后依然报这个错`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:4! (when checking argument for argument index in method wrapper_CUDA__index_select)`

**Comment by HansenJohn** [comment]
qwen2.5VL可以在v100上运行吗
