### ISSUE TITLE
Qwen2-vl 8张 48G 的显卡，启动每有报现存不够，但是推理图片报cuda out of memory？显存远远足够的啊

### ISSUE THREAD

**Issue by cqray1990** [QwenLM/Qwen2-VL#280]

**Comment by Horizontal666** [comment]
After using dataparallel(), I can use the example program it provides for single image inference, with 24GB of memory per GPU

**Comment by mind-animator-design** [comment]
我之前也报这个错，后来加上图片的最大像素就可以正常运行了：
{"type": "image", "image": img_path1,"max_pixels": 512 * 512,},

**Comment by jackhexiangyu12** [comment]
> 我之前也报这个错，后来加上图片的最大像素就可以正常运行了： {“type”： “image”， “image”： img_path1，“max_pixels”： 512 * 512，}，

请问在哪里添加的最大像素参数？

**Comment by aceliuchanghong** [comment]
> > 我之前也报这个错，后来加上图片的最大像素就可以正常运行了： {“type”： “image”， “image”： img_path1，“max_pixels”： 512 * 512，}，
> 
> 请问在哪里添加的最大像素参数？

messages里面
"messages": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "image": "no_git_oic/page_3.png",
                        "max_pixels": 512 * 512,
                    },
                    {
                        "type": "text",
                        "text": "还原文档,使用markdown格式输出",
                    },
                ],
            }
        ],

**Comment by aodexiusi1997** [comment]
> > > 我之前也报这个错，后来加上图片的最大像素就可以正常运行了： {“type”： “image”， “image”： img_path1，“max_pixels”： 512 * 512，}，
> > 
> > 
> > 请问在哪里添加的最大像素参数？
> 
> messages里面 "messages": [ { "role": "user", "content": [ { "type": "image", "image": "no_git_oic/page_3.png", "max_pixels": 512 * 512, }, { "type": "text", "text": "还原文档,使用markdown格式输出", }, ], } ],

![image](https://github.com/user-attachments/assets/61583e62-9489-4e3c-a049-179b84b4c2eb)
qinge请问这两个对于图片的max_pixels 的设置代表啥不同的含义吗

**Comment by Dineshkumar-Anandan-ZS0367** [comment]
I am getting accuracy loss to set the min and max pixels for this model. If not set i am getting cuda out of memory in A100 80GB machine also.

**Comment by gymbeijing** [comment]
@Dineshkumar-Anandan-ZS0367 Thank you for the information. Can I ask what's the min and max pixels you set? And how much accuracy loss did you get?

**Comment by Dineshkumar-Anandan-ZS0367** [comment]
@gymbeijing 

Configs,
min_pixels = 256*28*28
max_pixels = 1280*28*28

For both printed and handwritten text extraction as a key value pair i have the accuracy loss while extracting text.

if tuning this config to max_pixels = 2560*28*28, i got better accuracy

**Comment by InsaneGe** [comment]
> > 我之前也报这个错，后来加上图片的最大像素就可以正常运行了： {“type”： “image”， “image”： img_path1，“max_pixels”： 512 * 512，}，
> 
> 请问在哪里添加的最大像素参数？
you can see clearly in https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct#image-resolution-for-performance-boost

**Comment by LiDe2000** [comment]
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
                "max_pixels": 512 * 512,
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]
添加 "max_pixels": 512 * 512 可以得到解决

**Comment by LiDe2000** [comment]
> > > 我之前也报这个错，后来加上图片的最大像素就可以正常运行了： {“type”： “image”， “image”： img_path1，“max_pixels”： 512 * 512，}，
> > 
> > 
> > 请问在哪里添加的最大像素参数？
> 
> messages里面  消息里面 "messages": [ { "role": "user",  "角色": "用户" "content": [  "内容": [ { "type": "image",  "type": "image" "image": "no_git_oic/page_3.png","image": "no_git_oic/page_3.png" "max_pixels": 512 * 512,"max_pixels": 512 * 512 }, { "type": "text",  "type": "text" "text": "还原文档,使用markdown格式输出", }, ],  ] } ],  ]

实测可以解决

**Comment by LiDe2000** [comment]
> [!TIP]
>I added "max_pixels": 512 * 512 to message, 'cuda out of memory' is resolved. 
```python
messages = [
{
  "role": "user",
  "content": [
      {
          "type": "image",
          "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
          "max_pixels": 512 * 512,
      },
      {"type": "text", "text": "Describe this image."},
  ],
}
]
```
