### ISSUE TITLE
Does Qwen2VL support text-only input?

### ISSUE THREAD

**Issue by aiiph4** [QwenLM/Qwen2-VL#69]
I use Qwen-VL-7B-Instruct. I set the `image_inputs` and `video_inputs` both to be `None` in the following function:
```
    inputs = processor(
          text=[text],
          images=image_inputs,
          videos=video_inputs,
          padding=True,
          return_tensors="pt",
      )
```
The message is like:
```
[
          {
              "role": "user",
              "content": 'how are u?'
          }
]
```
Then I get the following error:
```
File "/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 641, in forward
    query_states, key_states = apply_multimodal_rotary_pos_emb(
  File "lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 185, in apply_multimodal_rotary_pos_emb
    cos = torch.cat([m[i % 3] for i, m in enumerate(cos.split(mrope_section, dim=-1))], dim=-1).unsqueeze(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
Does this mean Qwen-VL2 not support text-only input? Or what should I modify the code to support it? Thank u very much!

**Comment by kq-chen** [comment]
It's a known bug, and the [fix PR](https://github.com/huggingface/transformers/pull/33161) has been proposed and is awaiting merge. This issue only occurs with `attn_implementation="flash_attention_2"`.

For now, you can use the eager implementation:
model = Qwen2VLForConditionalGeneration.from_pretrained(
    model_path,
    torch_dtype="auto",
    device_map="auto",
)

**Comment by aiiph4** [comment]
Thanks for your swift reply! This solves my issue.

**Comment by mano3-1** [comment]
Hey,
My dataset has few datapoints without any images and rest with images. I could see we are assuming either images or videos present for each datapoint, is there a way to handle my case?
